theme = "lynx"
title = "Otto Berger"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Otto Berger"
  headline = "development, products"
  image = "img/image.jpeg"
  links = [
    { link = { href = "about/", text = "About & Impressum", target = "_self" } },
    { github = "https://github.com/otto802" },
    { linkedin = "https://www.linkedin.com/in/otto-berger/" },
    { instagram = "https://www.instagram.com/otto__berger/" },

     { dev = { href = "https://www.internetteamwettbewerb.de", text = "Team Competition" } },
     { dev = { href = "https://addons.thunderbird.net/en/thunderbird/addon/quickarchiver/", text = "QuickArchiver" } },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
